name: Run Campinas Script Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *' # Executa a cada 30 minutos
  workflow_dispatch:         # Adiciona a opção de execução manual


jobs:
  run-campinas-script:
    runs-on: ubuntu-latest  # Usa um ambiente Linux para execução
    name: Execute R Script
    steps:
 # Passo para obter os arquivos do repositório
      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2  # Configura o ambiente R

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::httr
            any::jsonlite
            any::janitor
            any::aws.s3
            any:arrow

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Campinas Script
        run: |
          Rscript upload_api.R  # Executa o seu script
