name: Run Campinas Script Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *' # Executa a cada 30 minutos
  workflow_dispatch:         # Adiciona a opção de execução manual


jobs:
  run-campinas-script:
    runs-on: ubuntu-latest  # Usa um ambiente Linux para execução
    name: Execute R Script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Passo para obter os arquivos do repositório

      - name: Setup R
        uses: r-lib/actions/setup-r@v2  # Configura o ambiente R

      - name: Install R packages
        run: |
          R -e 'install.packages(c("tidyverse", "httr", "jsonlite", "aws.s3", "arrow"))'
          
      - name: Run Campinas Script
        run: |
          Rscript upload_api.R  # Executa o seu script
